### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by danslocombe** [egnwd/homenum-revelio#2]
When I try and run webpack I get the error

```
ERROR in ./src/index.tsx
Module build failed: A file specified in tsconfig.json could not be found: /home/dan/projects/homenum-revelio/client/typings/index.d.ts
```

Which is a file that definitely doesn't exist.

**Comment by egnwd** [comment]
Sorry only just seen this running `typings install` in the client directory should install this, I'll add it to the read me
